creation:
    path: /create
    controller: App\Controller\HomeController::create
connection:
    path: /show/{id}
    controller: App\Controller\HomeController::showProjectInformations
#    requirements:
#        id: '\d+'
redisConnection:
    path: /redis
    controller: App\Controller\HomeController::redisConnection